id: 7c87fce9-4f4c-5713-b66a-183394c2a785
name: Mask System Power Settings Via Systemctl
description: No description provided
severity: High
queryFrequency: PT1H
queryPeriod: PT1H
triggerOperator: gt
triggerThreshold: 0
tactics:
- Persistence
- Impact
query: |-
  DeviceProcessEvents
  | where (ProcessCommandLine contains "suspend.target" or ProcessCommandLine contains "hibernate.target" or ProcessCommandLine contains "hybrid-sleep.target") and (ProcessCommandLine contains " mask" and FolderPath endswith "/systemctl")
version: 1.0.0
kind: Scheduled
relevantTechniques:
- T1653
entityMappings:
- entityType: Account
  fieldMappings:
  - identifier: Name
    columnName: InitiatingProcessAccountName
  - identifier: NTDomain
    columnName: InitiatingProcessAccountDomain
  - identifier: Sid
    columnName: InitiatingProcessAccountSid
- entityType: Host
  fieldMappings:
  - identifier: HostName
    columnName: DeviceName
  - identifier: AzureID
    columnName: DeviceId
- entityType: Process
  fieldMappings:
  - identifier: CommandLine
    columnName: ProcessCommandLine
- entityType: File
  fieldMappings:
  - identifier: Directory
    columnName: FolderPath
requiredDataConnectors:
- connectorId: MicrosoftThreatProtection
  dataTypes:
  - DeviceProcessEvents
