id: fa768091-ef9c-5209-a1f4-d9c558ab3e31
name: Using SettingSyncHost.exe as LOLBin
description: 'Detects using SettingSyncHost.exe to run hijacked binary Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_settingsynchost.yml | Source: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_lolbin_settingsynchost.yml'
severity: High
queryFrequency: PT1H
queryPeriod: PT1H
triggerOperator: gt
triggerThreshold: 0
tactics:
- PrivilegeEscalation
- Persistence
- Execution
- DefenseEvasion
query: |-
  DeviceProcessEvents
  | where (not((FolderPath startswith "C:\\Windows\\System32\\" or FolderPath startswith "C:\\Windows\\SysWOW64\\"))) and (InitiatingProcessCommandLine contains "cmd.exe /c" and InitiatingProcessCommandLine contains "RoamDiag.cmd" and InitiatingProcessCommandLine contains "-outputpath")
version: 1.0.0
kind: Scheduled
relevantTechniques:
- T1574
entityMappings:
- entityType: Account
  fieldMappings:
  - identifier: Name
    columnName: InitiatingProcessAccountName
  - identifier: NTDomain
    columnName: InitiatingProcessAccountDomain
  - identifier: Sid
    columnName: InitiatingProcessAccountSid
- entityType: Host
  fieldMappings:
  - identifier: HostName
    columnName: DeviceName
  - identifier: AzureID
    columnName: DeviceId
- entityType: Process
  fieldMappings:
  - identifier: CommandLine
    columnName: ProcessCommandLine
- entityType: File
  fieldMappings:
  - identifier: Directory
    columnName: FolderPath
requiredDataConnectors:
- connectorId: MicrosoftThreatProtection
  dataTypes:
  - DeviceProcessEvents
