id: 40142cfe-3d70-5fb0-aadd-f45ffd7fe9ab
name: New Application in AppCompat
description: No description provided
severity: Informational
queryFrequency: PT1H
queryPeriod: PT1H
triggerOperator: gt
triggerThreshold: 0
tactics:
- Execution
query: |-
  DeviceRegistryEvents
  | where RegistryKey endswith "\\AppCompatFlags\\Compatibility Assistant\\Store*"
version: 1.0.0
kind: Scheduled
relevantTechniques:
- T1204
entityMappings:
- entityType: Account
  fieldMappings:
  - identifier: Name
    columnName: InitiatingProcessAccountName
  - identifier: NTDomain
    columnName: InitiatingProcessAccountDomain
  - identifier: Sid
    columnName: InitiatingProcessAccountSid
- entityType: Host
  fieldMappings:
  - identifier: HostName
    columnName: DeviceName
  - identifier: AzureID
    columnName: DeviceId
- entityType: RegistryKey
  fieldMappings:
  - identifier: Key
    columnName: RegistryKey
requiredDataConnectors:
- connectorId: MicrosoftThreatProtection
  dataTypes:
  - DeviceRegistryEvents
