// Title: DMP/HDMP File Creation
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2023-09-07
// Level: low
// Description: Detects the creation of a file with the ".dmp"/".hdmp" extension. Often created by software during a crash. Memory dumps can sometimes contain sensitive information such as credentials. It's best to determine the source of the crash.
// MITRE Tactic: Uncategorized
// Tags: detection.threat-hunting, attack.stealth
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules-threat-hunting/windows/file/file_event/file_event_win_dump_file_creation.yml
// False Positives:
//   - Likely during crashes of software

DeviceFileEvents
| where FolderPath endswith ".dmp" or FolderPath endswith ".dump" or FolderPath endswith ".hdmp"