// Title: ESXi Syslog Configuration Change Via ESXCLI
// Author: Cedric Maurugeon
// Date: 2023-09-04
// Level: medium
// Description: Detects changes to the ESXi syslog configuration via "esxcli"
// MITRE Tactic: Execution
// Tags: attack.execution, attack.defense-impairment, attack.t1685, attack.t1690, attack.t1059.012
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_esxcli_syslog_config_change.yml
// False Positives:
//   - Legitimate administrative activities

DeviceProcessEvents
| where ProcessCommandLine contains " set" and (ProcessCommandLine contains "system" and ProcessCommandLine contains "syslog" and ProcessCommandLine contains "config") and FolderPath endswith "/esxcli"