// Title: Windows Defender Exclusion List Modified
// Author: @BarryShooshooga
// Date: 2019-10-26
// Level: medium
// Description: Detects modifications to the Windows Defender exclusion registry key. This could indicate a potentially suspicious or even malicious activity by an attacker trying to add a new exclusion in order to bypass security.
// MITRE Tactic: Uncategorized
// Tags: attack.defense-impairment, attack.t1685
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/builtin/security/win_security_windows_defender_exclusions_registry_modified.yml
// False Positives:
//   - Intended exclusions by administrators

DeviceRegistryEvents
| where RegistryKey endswith "\\Microsoft\\Windows Defender\\Exclusions*"