// Title: Registry Hive File Staged Outside Standard User Profile Path
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2026-07-23
// Level: high
// Description: Detects the creation of a registry hive file (UsrClass.dat or NTUSER.DAT) outside of the standard user profile path.
// These files generally contain various user-specific registry settings and are typically located in the user's profile directory.
// Staging these files outside of the standard path can be indicative of an attacker attempting to manipulate user registry settings
// for persistence, privilege escalation, or dump user registry hives for credential harvesting.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.t1548, attack.credential-access, attack.t1003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/file/file_event/file_event_win_susp_registry_hive_file_creation.yml
// False Positives:
//   - Backup or profile migration software
//   - Forensic acquisition tools

DeviceFileEvents
| where (FolderPath endswith "\\UsrClass.dat" or FolderPath endswith "\\NTUSER.DAT") and (not((FolderPath matches regex "(?i)^C:\\\\Users\\\\[^\\\\]+\\\\NTUSER\\.DAT$" or (FolderPath startswith "C:\\Windows\\System32\\config\\" or FolderPath startswith "C:\\Windows\\SYSVOL\\" or FolderPath startswith "C:\\Windows\\ServiceProfiles\\") or FolderPath endswith "\\AppData\\Local\\Microsoft\\Windows\\UsrClass.dat")))