// Title: Disable Microsoft Defender Firewall via Registry
// Author: frack113
// Date: 2022-01-09
// Level: medium
// Description: Adversaries may disable or modify system firewalls in order to bypass controls limiting network usage
// MITRE Tactic: Uncategorized
// Tags: attack.defense-impairment, attack.t1686.003
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_disable_defender_firewall.yml

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000000)" and RegistryKey endswith "\\Services\\SharedAccess\\Parameters\\FirewallPolicy*" and RegistryKey endswith "\\EnableFirewall"