// Title: Potential AutoLogger Sessions Tampering
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-01
// Level: high
// Description: Detects tampering with autologger trace sessions which is a technique used by attackers to disable logging.
// The AutoLogger event tracing session records events up that occur early in the operating system boot process.
// Applications and device drivers can use the AutoLogger session to capture traces before the user logs in, and also used by security solutions as telemetry source.
// Adversaries may disable these sessions to evade detection and prevent security monitoring of early boot activities and system events.
// MITRE Tactic: Uncategorized
// Tags: attack.defense-impairment, attack.t1685.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_disable_autologger_sessions.yml

DeviceRegistryEvents
| where (RegistryKey endswith "\\Control\\WMI\\Autologger*" and (RegistryValueData =~ "DWORD (0x00000000)" and (RegistryKey contains "\\EventLog-" or RegistryKey contains "\\Defender") and (RegistryKey endswith "\\Enabled" or RegistryKey endswith "\\Start"))) and (not(((InitiatingProcessFolderPath endswith "\\MsMpEng.exe" and (InitiatingProcessFolderPath startswith "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\" or InitiatingProcessFolderPath startswith "C:\\Program Files\\Windows Defender\\" or InitiatingProcessFolderPath startswith "C:\\Program Files (x86)\\Windows Defender\\") and (RegistryKey endswith "\\DefenderApiLogger*" or RegistryKey endswith "\\DefenderAuditLogger*")) or InitiatingProcessFolderPath =~ "C:\\Windows\\system32\\wevtutil.exe")))