// Title: Hypervisor Enforced Paging Translation Disabled
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2024-07-05
// Level: high
// Description: Detects changes to the "DisableHypervisorEnforcedPagingTranslation" registry value. Where the it is set to "1" in order to disable the Hypervisor Enforced Paging Translation feature.
// MITRE Tactic: Uncategorized
// Tags: attack.defense-impairment, attack.t1685
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/registry/registry_set/registry_set_deviceguard_hypervisorenforcedpagingtranslation_disabled.yml

DeviceRegistryEvents
| where RegistryValueData =~ "DWORD (0x00000001)" and RegistryKey endswith "\\DisableHypervisorEnforcedPagingTranslation"