// Title: ETW Logging Tamper In .NET Processes Via CommandLine
// Author: Roberto Rodriguez (Cyb3rWard0g), OTR (Open Threat Research)
// Date: 2020-05-02
// Level: high
// Description: Detects changes to environment variables related to ETW logging via the CommandLine.
// This could indicate potential adversaries stopping ETW providers recording loaded .NET assemblies.
// MITRE Tactic: Uncategorized
// Tags: attack.defense-impairment, attack.t1685
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_susp_etw_modification_cmdline.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where ProcessCommandLine contains "COMPlus_ETWEnabled" or ProcessCommandLine contains "COMPlus_ETWFlags"