// Title: New DMSA Service Account Created in Specific OUs
// Author: Swachchhanda Shrawan Poudel (Nextron Systems)
// Date: 2025-05-24
// Level: medium
// Description: Detects the creation of a dMSASvc account using the New-ADServiceAccount cmdlet in certain OUs.
// The fact that the Cmdlet is used to create a dMSASvc account in a specific OU is highly suspicious.
// It is a pattern trying to exploit the BadSuccessor privilege escalation vulnerability in Windows Server 2025.
// On top of that, if the user that is creating the dMSASvc account is not a legitimate administrator or does not have the necessary permissions,
// it is a strong signal of an attempted or successful abuse of the BaDSuccessor vulnerability for privilege escalation within the Windows Server 2025 Active Directory environment.
// MITRE Tactic: Privilege Escalation
// Tags: attack.privilege-escalation, attack.initial-access, attack.persistence, attack.stealth, attack.t1078.002, attack.t1098
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_create_new_dmsasvc_account.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "New-ADServiceAccount" and ProcessCommandLine contains "-CreateDelegatedServiceAccount" and ProcessCommandLine contains "-path") and ((FolderPath endswith "\\powershell.exe" or FolderPath endswith "\\pwsh.exe" or FolderPath endswith "\\powershell_ise.exe") or (ProcessVersionInfoOriginalFileName in~ ("powershell.exe", "pwsh.dll", "powershell_ise.exe")))