// Title: Arbitrary File Download Via PresentationHost.EXE
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-19
// Level: medium
// Description: Detects usage of "PresentationHost" which is a utility that runs ".xbap" (Browser Applications) files to download arbitrary files
// MITRE Tactic: Execution
// Tags: attack.execution, attack.stealth, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_presentationhost_download.yml

DeviceProcessEvents
| where (ProcessCommandLine contains "http://" or ProcessCommandLine contains "https://" or ProcessCommandLine contains "ftp://") and (FolderPath endswith "\\presentationhost.exe" or ProcessVersionInfoOriginalFileName =~ "PresentationHost.exe")