// Title: Suspicious Msiexec Execute Arbitrary DLL
// Author: frack113
// Date: 2022-01-16
// Level: medium
// Description: Adversaries may abuse msiexec.exe to proxy execution of malicious payloads.
// Msiexec.exe is the command-line utility for the Windows Installer and is thus commonly associated with executing installation packages (.msi)
// MITRE Tactic: Uncategorized
// Tags: attack.stealth, attack.t1218.007
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_msiexec_execute_dll.yml
// False Positives:
//   - Legitimate script

DeviceProcessEvents
| where ((ProcessCommandLine contains " -Y" or ProcessCommandLine contains " /Y" or ProcessCommandLine contains " –Y" or ProcessCommandLine contains " —Y" or ProcessCommandLine contains " ―Y") and FolderPath endswith "\\msiexec.exe") and (not((ProcessCommandLine contains "\\MsiExec.exe\" /Y \"C:\\Program Files\\" or ProcessCommandLine contains "\\MsiExec.exe\" /Y \"C:\\Program Files (x86)\\" or ProcessCommandLine contains "\\MsiExec.exe\" /Y \"C:\\Windows\\System32\\" or ProcessCommandLine contains "\\MsiExec.exe\" /Y \"C:\\Windows\\SysWOW64\\")))