// Title: Registry Manipulation via WMI Stdregprov
// Author: Daniel Koifman (KoifSec)
// Date: 2025-07-30
// Level: medium
// Description: Detects the usage of wmic.exe to modify Windows registry via the WMI StdRegProv class write methods (CreateKey, DeleteKey, SetStringValue, etc.).
// This behaviour could be potentially suspicious because it uses an alternative method to modify registry keys instead of legitimate registry tools like reg.exe or regedit.exe.
// Attackers specifically choose this technique to evade detection and bypass security monitoring focused on traditional registry modification commands.
// MITRE Tactic: Execution
// Tags: attack.execution, attack.t1047, attack.persistence, attack.defense-impairment, attack.t1112
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_wmic_stdregprov_reg_modification.yml
// False Positives:
//   - Legitimate administrative activity

DeviceProcessEvents
| where ((ProcessCommandLine contains "CreateKey" or ProcessCommandLine contains "DeleteKey" or ProcessCommandLine contains "DeleteValue" or ProcessCommandLine contains "SetBinaryValue" or ProcessCommandLine contains "SetDWORDValue" or ProcessCommandLine contains "SetExpandedStringValue" or ProcessCommandLine contains "SetMultiStringValue" or ProcessCommandLine contains "SetQWORDValue" or ProcessCommandLine contains "SetSecurityDescriptor" or ProcessCommandLine contains "SetStringValue") and (ProcessCommandLine contains "stdregprov" and ProcessCommandLine contains "call")) and (FolderPath endswith "\\wmic.exe" or ProcessVersionInfoOriginalFileName =~ "wmic.exe")