// Title: Sysmon Driver Unloaded Via Fltmc.EXE
// Author: Kirill Kiryanov, oscd.community
// Date: 2019-10-23
// Level: high
// Description: Detects possible Sysmon filter driver unloaded via fltmc.exe
// MITRE Tactic: Uncategorized
// Tags: attack.stealth, attack.defense-impairment, attack.t1070, attack.t1685, attack.t1685.001
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_fltmc_unload_driver_sysmon.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where (ProcessCommandLine contains "unload" and ProcessCommandLine contains "sysmon") and (FolderPath endswith "\\fltMC.exe" or ProcessVersionInfoOriginalFileName =~ "fltMC.exe")