// Title: DeviceCredentialDeployment Execution
// Author: Nasreddine Bencherchali (Nextron Systems)
// Date: 2022-08-19
// Level: medium
// Description: Detects the execution of DeviceCredentialDeployment to hide a process from view.
// MITRE Tactic: Uncategorized
// Tags: attack.stealth, attack.t1218
// Reference: https://github.com/SigmaHQ/sigma/blob/master/rules/windows/process_creation/proc_creation_win_device_credential_deployment.yml
// False Positives:
//   - Unlikely

DeviceProcessEvents
| where FolderPath endswith "\\DeviceCredentialDeployment.exe"